export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const MARK_COMPLETED = "MARK_COMPLETED";
export const MARK_INCOMPLETED = "MARK_INCOMPLETED";
export const FILTER_TODOS = "FILTER_TODOSO";
export const MAKR_ALL_COMPLETED = "MAKR_ALL_COMPLETED";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";

